name: Homelab Build and Run
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: docker_CT
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
        shell: bash

      - name: Log in to Local Registry
        run: |
          docker login harbor.local.jushack.tech -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
        shell: bash

      - name: Build and Push Multi-arch Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag harbor.local.jushack.tech/docker/dumbpad:latest \
            --push \
            .
        shell: bash

      - name: Deploy to server using SSH
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_PASS: ${{ secrets.SSH_PASSWORD }}
        run: |
          # Create deployment script
          DEPLOY_SCRIPT="""
          mkdir -p /app/data
          
          # Login to registry on deployment server
          docker login harbor.local.jushack.tech -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
          
          # Pull the image (will automatically select amd64)
          docker pull harbor.local.jushack.tech/docker/dumbpad:latest
          
          # Stop and remove existing container if it exists
          docker stop dumbpad-container || true
          docker rm dumbpad-container || true
          
          # Create and start new container
          docker run -d \
            --name dumbpad \
            --platform linux/amd64 \
            -p 3000:3000 \
            -v /app/data:/app/data \
            --restart unless-stopped \
            harbor.local.jushack.tech/docker/dumbpad:latest
          
          # Verify container is running
          docker ps | grep dumbpad-container
          """
          
          export SSHPASS="${SSH_PASS}"
          sshpass -e ssh -o StrictHostKeyChecking=no ${SSH_USER}@192.168.248.79 "${DEPLOY_SCRIPT}"
        shell: bash
