name: Homelab Build and Run
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

#      - name: Log in to Local Registry
#        run: |
#          echo "Logging into local registry"
#          docker login 192.168.248.131 -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t 192.168.248.131/docker/dumbpad:latest .

#      - name: Push Docker Image
#        run: |
#          docker push 192.168.248.131/docker/dumbpad:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 192.168.248.79
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}    # Using password authentication
          port: 22
          script_stop: true
          script: |
            # Create data directory if it doesn't exist
            mkdir -p /app/data
            
            # Pull the latest image
            docker pull 192.168.248.131/docker/dumbpad:latest
            
            # Stop and remove existing container if it exists
            docker stop dumbpad-container || true
            docker rm dumbpad-container || true
            
            # Create and start new container with specified parameters
            docker run -d \
              --name dumbpad-container \
              -p 3000:3000 \
              -v /app/data:/app/data \
              --restart unless-stopped \
              192.168.248.131/docker/dumbpad:latest
            
            # Verify container is running
            docker ps | grep dumbpad-container
