name: Homelab Build and Run
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: docker_CT
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

#      - name: Log in to Local Registry
#        run: |
#          docker login 192.168.248.131 -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
#        shell: bash

      - name: Build Docker Image
        run: |
          docker build -t 192.168.248.131/docker/dumbpad:latest .
        shell: bash

#      - name: Push Docker Image
#        run: |
#          docker push 192.168.248.131/docker/dumbpad:latest
#        shell: bash

      - name: Deploy to server using SSH
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_PASS: ${{ secrets.SSH_PASSWORD }}
        run: |
          # Create deployment script
          DEPLOY_SCRIPT="""
          mkdir -p /app/data
          docker pull 192.168.248.131/docker/dumbpad:latest
          docker stop dumbpad-container || true
          docker rm dumbpad-container || true
          docker run -d \
            --name dumbpad-container \
            -p 3000:3000 \
            -v /app/data:/app/data \
            --restart unless-stopped \
            192.168.248.131/docker/dumbpad:latest
          docker ps | grep dumbpad-container
          """
          
          # Using sshpass which is typically available on macOS
          export SSHPASS="${SSH_PASS}"
          sshpass -e ssh -o StrictHostKeyChecking=no ${SSH_USER}@192.168.248.79 "${DEPLOY_SCRIPT}"
        shell: bash
