name: Homelab Build and Run
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: docker_CT
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
        shell: bash

      - name: Log in to Local Registry
        run: |
          docker login harbor.local.jushack.tech -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
        shell: bash

      - name: Build and Push Multi-arch Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag harbor.local.jushack.tech/docker/dumbdo:latest \
            --push \
            .
        shell: bash

      - name: Deploy to server using SSH
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_PASS: ${{ secrets.SSH_PASSWORD }}
        run: |
          # Create deployment script with error handling
          DEPLOY_SCRIPT="""
          set -e  # Exit on error
          
          echo 'Creating data directory...'
          mkdir -p /app/data
          
          echo 'Logging into registry...'
          docker login harbor.local.jushack.tech -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
          
          echo 'Pulling latest image...'
          docker pull harbor.local.jushack.tech/docker/dumbdo:latest
          
          echo 'Stopping old container...'
          docker stop dumbdo || true
          docker rm dumbdo || true
          
          echo 'Starting new container...'
          docker run -d \
            --name dumbdo \
            --platform linux/amd64 \
            -p 3000:3000 \
            -v /app/data:/app/data \
            --restart unless-stopped \
            harbor.local.jushack.tech/docker/dumbdo:latest
          
          echo 'Verifying container status...'
          docker ps | grep dumbdo || echo 'Container status check failed, but container might still be running'
          
          # Check if container is actually running regardless of grep
          if docker ps --format '{{.Names}}' | grep -q '^dumbdo$'; then
            echo 'Container is running successfully'
            exit 0
          else
            echo 'Container failed to start'
            exit 1
          fi
          """
          
          export SSHPASS="${SSH_PASS}"
          sshpass -e ssh -o StrictHostKeyChecking=no ${SSH_USER}@192.168.248.79 "${DEPLOY_SCRIPT}"
        shell: bash
        continue-on-error: true  # Optional: if you want the workflow to succeed even with non-zero exit
